# Generated by Django 4.2.3 on 2023-07-16 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Home',
            new_name='Usuario',
        ),
    ]
